language: go
go:
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2
install:
  - go get -t -v ./...
notifications:
  email:
    recipients: parnurzeal@gmail.com
    on_success: change
    on_failure: always
